* Shortcut
** C-m: Return，can replay return key.

* Hooks

Most major modes run one or more mode hooks as the last step of initialization. 
Mode hooks are a convenient way to customize the behavior of individual modes; 
they are always normal. For example, here's how to set up a hook to turn on
Auto Fill mode in Text mode and other modes based on Text mode:

#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook 'auto-fill-mode)
#+END_SRC

* How to use emacs helps:

You should ask Emacs this question: C-h i, choose the Elisp manual (m Elisp), 
and search the index for "defvar" (i defvar). That takes you to node Defining 
Variables.

Emacs tells you that defvar allows attaching a doc string, and that if 
the variable already has a value then it does nothing.

It also tells you about the use of defvar with no value to be assigned: 
(defvar foo). It tells you that that declares the variable to be dynamically scoped.

setq has none of those properties.

defvar and setq are similar, but not quite the same, in Emacs Lisp and Common Lisp.
* Ivy 批量修改
https://zhuanlan.zhihu.com/p/22687261
